# This code was generated by ChatGPT
# Assignment: given a DNA string, return the reverse complement.

def reverse_complement(dna_string):
    complement = {'A': 'T', 'T': 'A', 'C': 'G', 'G': 'C'}  # Define the complement for each base
    reverse = dna_string[::-1]  # Reverse the string
    complemented = [complement[base] for base in reverse]
    return ''.join(complemented)

# Input
dna_string = input("Enter the DNA string: ").strip()

# Output
reverse_comp = reverse_complement(dna_string)
print(reverse_comp)
